package com.vault.theguardian.notification;

public enum NotificationType {
    WELCOME,

    SUBSCRIPTION_ACTIVATED,
    SUBSCRIPTION_CANCELLED,
    SUBSCRIPTION_EXPIRED,

    BACKUP_CREATED,
    BACKUP_RESTORED,

    PASSWORD_ADDED,
    CARD_ADDED,
    DOCUMENT_ADDED,

    NOTE_ADDED,
    NOTE_UPDATED,
    NOTE_DELETED,

    FAMILY_MEMBER_ADDED,
    FAMILY_MEMBER_REMOVED,

    EMERGENCY_CONTACT_ADDED,
    EMERGENCY_CONTACT_REMOVED,
    EMERGENCY_ACCESS_REQUESTED,
    EMERGENCY_ACCESS_APPROVED,
    EMERGENCY_ACCESS_DENIED,
    EMERGENCY_ACCESS_AVAILABLE,
    EMERGENCY_VAULT_VIEWED,

    ESTATE_PLAYBOOK_CREATED,
    ESTATE_PLAYBOOK_UPDATED,
    ESTATE_PLAYBOOK_ARCHIVED,
    ESTATE_PLAYBOOK_RELEASED,
    ESTATE_PLAYBOOK_VIEWED,
    ESTATE_PLAYBOOK_COMPLETED,
    ESTATE_PLAYBOOK_CANCELLED,

    RECOVERY_KIT_CREATED,
    RECOVERY_KIT_USED,
    RECOVERY_KIT_REVOKED,
    ACCOUNT_RESET_VAULT_ERASED,

    DURESS_ALERT,

    INCIDENT_LOCKDOWN_STARTED,
    INCIDENT_PASSWORD_ROTATED,
    INCIDENT_LOCKDOWN_COMPLETED,
    INCIDENT_LOCKDOWN_RECOVERED,
    INCIDENT_LOCKDOWN_CANCELLED,

    SECURITY_ALERT,
    SECURITY_SCAN_ALERT,
    PASSWORD_BREACHED,
    NEW_DEVICE_LOGIN,
    SESSION_REVOKED,
    SYSTEM
}
