spring.application.name=user-account-service

server.address=0.0.0.0
server.port=${PORT:8087}

management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always

services.auth.url=${AUTH_SERVICE_URL:http://localhost:8081}
services.notification.url=${NOTIFICATION_SERVICE_URL:http://localhost:8082}
services.subscription.url=${SUBSCRIPTION_SERVICE_URL:http://localhost:8083}
services.vault.url=${VAULT_SERVICE_URL:http://localhost:8084}
services.access-sharing.url=${ACCESS_SHARING_SERVICE_URL:http://localhost:8085}
services.backup-recovery.url=${BACKUP_RECOVERY_SERVICE_URL:http://localhost:8086}
internal.service.key=${INTERNAL_SERVICE_KEY}
