spring.application.name=theguardian

# Database
spring.datasource.url=${DATABASE_URL}
spring.datasource.username=${DATABASE_USERNAME}
spring.datasource.password=${DATABASE_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false

# Flyway
spring.flyway.enabled=true
spring.flyway.baseline-on-migrate=true

# JWT
jwt.secret=${JWT_SECRET}
jwt.expiration=${JWT_EXPIRATION}

# File upload properties
spring.servlet.multipart.max-file-size=25MB
spring.servlet.multipart.max-request-size=25MB
server.tomcat.max-swallow-size=25MB

# Document encryption secret
vault.document.secret=${VAULT_DOCUMENT_SECRET}

# Gmail API Email Sending
GMAIL_CLIENT_ID=${GMAIL_CLIENT_ID}
GMAIL_CLIENT_SECRET=${GMAIL_CLIENT_SECRET}
GMAIL_REFRESH_TOKEN=${GMAIL_REFRESH_TOKEN}
GMAIL_FROM=${GMAIL_FROM}

# Demo mode
# true = email failure will not break signup/login flow
DEMO_MODE=${DEMO_MODE:true}

# Network Properties
server.address=0.0.0.0
server.port=${PORT:8080}

# Backup secret key
vault.backup.secret=${BACKUP_SECRET}