ALTER TABLE family_members
    ADD COLUMN IF NOT EXISTS share_passwords BOOLEAN NOT NULL DEFAULT TRUE,
    ADD COLUMN IF NOT EXISTS share_cards BOOLEAN NOT NULL DEFAULT FALSE,
    ADD COLUMN IF NOT EXISTS share_documents BOOLEAN NOT NULL DEFAULT FALSE;
