ALTER TABLE cards
    ADD COLUMN IF NOT EXISTS encrypted_notes TEXT,
    ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP;

UPDATE cards
SET updated_at = COALESCE(updated_at, created_at, CURRENT_TIMESTAMP)
WHERE updated_at IS NULL;

ALTER TABLE cards
    ALTER COLUMN updated_at SET DEFAULT CURRENT_TIMESTAMP;
