package com.vault.theguardian.notificationservice.notification;

public enum NotificationType {
    WELCOME,

    TWO_FACTOR_ENABLED,
    TWO_FACTOR_DISABLED,

    SUBSCRIPTION_ACTIVATED,
    SUBSCRIPTION_CANCELLED,
    SUBSCRIPTION_EXPIRED,

    BACKUP_CREATED,
    BACKUP_RESTORED,

    PASSWORD_ADDED,
    CARD_ADDED,
    DOCUMENT_ADDED,

    NOTE_ADDED,
    NOTE_UPDATED,
    NOTE_DELETED,

    FAMILY_MEMBER_ADDED,
    FAMILY_MEMBER_REMOVED,

    EMERGENCY_CONTACT_ADDED,
    EMERGENCY_CONTACT_REMOVED,
    EMERGENCY_ACCESS_REQUESTED,
    EMERGENCY_ACCESS_APPROVED,
    EMERGENCY_ACCESS_DENIED,
    EMERGENCY_ACCESS_AVAILABLE,
    EMERGENCY_VAULT_VIEWED,

    SAFETY_CHECK_CONFIGURED,
    SAFETY_CHECK_COMPLETED,
    SAFETY_CHECK_GRACE_STARTED,
    SAFETY_CHECK_TRIGGERED,
    SAFETY_CHECK_DISABLED,

    RECOVERY_KIT_CREATED,
    RECOVERY_KIT_USED,
    RECOVERY_KIT_REVOKED,
    ACCOUNT_RESET_VAULT_ERASED,

    RECOVERY_CIRCLE_CONFIGURED,
    RECOVERY_CIRCLE_DISABLED,
    RECOVERY_CIRCLE_MEMBER_ADDED,
    RECOVERY_CIRCLE_APPROVAL_REQUESTED,
    RECOVERY_CIRCLE_REQUEST_STARTED,
    RECOVERY_CIRCLE_VOTE_RECORDED,
    RECOVERY_CIRCLE_APPROVED,
    RECOVERY_CIRCLE_DENIED,
    RECOVERY_CIRCLE_CANCELLED,
    RECOVERY_CIRCLE_COMPLETED,

    ESTATE_PLAYBOOK_CREATED,
    ESTATE_PLAYBOOK_UPDATED,
    ESTATE_PLAYBOOK_ARCHIVED,
    ESTATE_PLAYBOOK_RELEASED,
    ESTATE_PLAYBOOK_VIEWED,
    ESTATE_PLAYBOOK_COMPLETED,
    ESTATE_PLAYBOOK_CANCELLED,

    CONTINUITY_DRILL_STARTED,
    CONTINUITY_DRILL_ACK_REQUESTED,
    CONTINUITY_DRILL_ACKNOWLEDGED,
    CONTINUITY_DRILL_COMPLETED,
    CONTINUITY_DRILL_EXPIRED,
    CONTINUITY_DRILL_CANCELLED,

    DURESS_ALERT,

    INCIDENT_LOCKDOWN_STARTED,
    INCIDENT_PASSWORD_ROTATED,
    INCIDENT_LOCKDOWN_COMPLETED,
    INCIDENT_LOCKDOWN_RECOVERED,
    INCIDENT_LOCKDOWN_CANCELLED,

    SECURITY_ALERT,
    SECURITY_SCAN_ALERT,
    PASSWORD_BREACHED,
    NEW_DEVICE_LOGIN,
    SESSION_REVOKED,
    SYSTEM
}
