package com.vault.theguardian.notificationservice.notification;

public enum NotificationType {
    WELCOME,

    SUBSCRIPTION_ACTIVATED,
    SUBSCRIPTION_CANCELLED,
    SUBSCRIPTION_EXPIRED,

    BACKUP_CREATED,
    BACKUP_RESTORED,

    PASSWORD_ADDED,
    CARD_ADDED,
    DOCUMENT_ADDED,

    NOTE_ADDED,
    NOTE_UPDATED,
    NOTE_DELETED,

    FAMILY_MEMBER_ADDED,
    FAMILY_MEMBER_REMOVED,

    EMERGENCY_CONTACT_ADDED,
    EMERGENCY_CONTACT_REMOVED,
    EMERGENCY_ACCESS_REQUESTED,
    EMERGENCY_ACCESS_APPROVED,
    EMERGENCY_ACCESS_DENIED,
    EMERGENCY_ACCESS_AVAILABLE,
    EMERGENCY_VAULT_VIEWED,

    RECOVERY_KIT_CREATED,
    RECOVERY_KIT_USED,
    RECOVERY_KIT_REVOKED,
    ACCOUNT_RESET_VAULT_ERASED,

    SECURITY_ALERT,
    SECURITY_SCAN_ALERT,
    PASSWORD_BREACHED,
    NEW_DEVICE_LOGIN,
    SESSION_REVOKED,
    SYSTEM
}
