package com.vault.theguardian.emergency;

public enum EmergencyAuditAction {
    CONTACT_CREATED,
    CONTACT_UPDATED,
    CONTACT_DELETED,
    ACCESS_REQUESTED,
    ACCESS_APPROVED,
    ACCESS_DENIED,
    ACCESS_AVAILABLE,
    EMERGENCY_VAULT_OPENED,
    EMERGENCY_ITEM_VIEWED,
    REQUEST_CANCELLED,
    SAFETY_CHECK_CONFIGURED,
    SAFETY_CHECK_COMPLETED,
    SAFETY_CHECK_GRACE_STARTED,
    SAFETY_CHECK_TRIGGERED,
    SAFETY_CHECK_DISABLED
}
