package com.vault.theguardian.emergency;

public enum EmergencyAuditAction {
    CONTACT_CREATED,
    CONTACT_UPDATED,
    CONTACT_DELETED,
    ACCESS_REQUESTED,
    ACCESS_APPROVED,
    ACCESS_DENIED,
    ACCESS_AVAILABLE,
    EMERGENCY_VAULT_OPENED,
    EMERGENCY_ITEM_VIEWED,
    REQUEST_CANCELLED
}
